language: php
php:
- 7.1
- 7.2
- 7.3

env:
- PHP_BIN=php
- PHP_BIN=php-cgi

before_install:
- phpenv config-rm xdebug.ini || return 0 # Turn off XDebug

install:
- travis_retry composer install # Composer

script:
- vendor/bin/tester -p $PHP_BIN tests -s # Tests

sudo: false

cache:
  directories:
  - $HOME/.composer/cache